name: Make Image for tbb

on:
  push :
    paths:
        - '.github/workflows/bashtbb.yml'


env:
  DOCKER_BUILDKIT: 1
  DEBIAN_FRONTEND: noninteractive
  RBM_NUM_PROCS: 16

jobs:
  stage1:
    name: tbb stage1
    runs-on: ubuntu-latest
    steps:
      - name: Free 80GB
        run: |
          sudo rm -rf "/usr/local/"
          sudo rm -rf "/usr/share/"
          sudo rm -rf "/opt/"
          
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 69000
          swap-size-mb: 12228
          temp-reserve-mb: 8
          remove-dotnet: 'false'
          remove-android: 'false'
          remove-haskell: 'false'

      - name: Generate Builder Script
        run: |
          cat >> bscript.sh << EOF
          apt-get update
          apt install -y -qq wget git build-essential vim curl
          apt install -y -qq libyaml-libyaml-perl libtemplate-perl libdatetime-perl \
                             libio-handle-util-perl libio-all-perl \
                             libio-captureoutput-perl libjson-perl libpath-tiny-perl \
                             libstring-shellquote-perl libsort-versions-perl \
                             libdigest-sha-perl libdata-uuid-perl libdata-dump-perl \
                             libfile-copy-recursive-perl libfile-slurp-perl git \
                             uidmap
          rm -rf /var/lib/apt/lists/* 
          usermod --add-subuids 1000000-1099999 --add-subgids 1000000-1099999 root
          git config --global http.postBuffer 524288000
          git config --global https.postBuffer 524288000
          git config --global http.sslVerify false
          git config --global https.sslVerify false
          git config --global core.compression -1
          git clone https://gitlab.torproject.org/tpo/applications/tor-browser-build.git
          cd tor-browser-build
          make submodule-update
          cd rbm
          rm -fr container
          wget https://gitlab.torproject.org/tpo/applications/rbm/-/raw/cad40965ce1204936a0df71c405bf0393b534ef9/container
          chmod 777 container
          cd ..
          make fetch
          make get_gradle_dependencies_list-android-components
          cd /home
          rm bscript.sh
          EOF
          
#          make cargo_vendor-application-services
#          make cargo_vendor-cbindgen-android
#          make cargo_vendor-cbindgen
#          make cargo_vendor-lucetc
#          make cargo_vendor-uniffi-rs          

      - name: Fetch and Build
        shell: 'script -q -e -c "bash {0}"'
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker run --interactive --tty --detach --privileged --name tbb ubuntu:22.04
          docker cp bscript.sh tbb:/home/
          docker exec tbb bash -c "cd /home && chmod +x bscript.sh && ./bscript.sh "
          docker commit tbb mohsen7s/tbb:stage1
          docker push mohsen7s/tbb:stage1

  stage2:
    name: tbb stage2
    runs-on: ubuntu-latest
    needs: stage1
    steps:
      - name: Free 80GB
        run: |
          sudo rm -rf "/usr/local/"
          sudo rm -rf "/usr/share/"
          sudo rm -rf "/opt/"
          
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 69000
          swap-size-mb: 12228
          temp-reserve-mb: 8
          remove-dotnet: 'false'
          remove-android: 'false'
          remove-haskell: 'false'

      - name: Generate Builder Script
        run: |
          cat >> bscript.sh << EOF
          cd tor-browser-build
          make submodule-update
          make fetch
          make get_gradle_dependencies_list-application-services
          rm /home/bscript.sh
          EOF
          

      - name: Fetch and Build
        shell: 'script -q -e -c "bash {0}"'
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker run --interactive --tty --detach --privileged --name tbb mohsen7s/tbb:stage1
          docker cp bscript.sh tbb:/home/
          docker exec tbb bash -c "cd /home && chmod +x bscript.sh && ./bscript.sh "
          docker commit tbb mohsen7s/tbb:stage2
          docker push mohsen7s/tbb:stage2

