name: Checkpoint Builder

on:
  push :
    paths:
        - '.github/workflows/brave.yml'


env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  browser:
    name: Build Tor Browser
    runs-on: ubuntu-18.04
    steps:
                            
#      - name: Free 80GB
#        run: |
#          sudo rm -rf "/usr/local/"
#          sudo rm -rf "/usr/share/"
#          sudo rm -rf "/opt/"
          
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 4096
          swap-size-mb: 2048
          temp-reserve-mb: 2048
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
      
      - name: Build brave
        run: |
          #curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
          #sudo apt update
          #sudo apt install nodejs
          #echo "Brave Point"
          sudo apt update
          sudo apt install -y build-essential libgnome-keyring-dev python-setuptools npm  nodejs

          git clone https://github.com/brave/brave-browser.git
          cd brave-browser
          npm install
          #npm run init -- --target_os=android --target_arch=arm
          npm run build -- --target_os=android --target_arch=arm
