name: Make Image for tbb

on:
  push :
    paths:
        - '.github/workflows/buildwithpruner.yml'
      
env:
  DOCKER_BUILDKIT: 1
  DEBIAN_FRONTEND: noninteractive
  RBM_NUM_PROCS: 16

jobs:
  stage1:
    name: tbb stage3
    runs-on: ubuntu-latest
    steps:
    
      - name: Start Build
        uses: mohsen7s/runner-prune-except-docker@main
        with:
          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          use-image-name: ubuntu:22.04
          step-image-name: mohsen7s/tbb:stage4
          run-command: |
            cd /home
            mkdir zzz
            ls
            df -h 
            echo "hello from run cmd"
                    
      - name: Say hello
        run: |
          echo hi
           
