name: Make Image for tbb

on:
  push :
    paths:
        - '.github/workflows/tbb_make_docker.yml'


env:
  DEBIAN_FRONTEND: noninteractive
  RBM_NUM_PROCS: 16

jobs:
  browser:
    name: tbb fetch and gradle fenix
    runs-on: ubuntu-latest
    steps:

      - name: Free 80GB
        run: |
          sudo rm -rf "/usr/local/"
          sudo rm -rf "/usr/share/"
          sudo rm -rf "/opt/"
  
          #sudo find / -type d -exec du --threshold=100000000 -h -a  {} +
          
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 69000
          swap-size-mb: 12228
          temp-reserve-mb: 8
          remove-dotnet: 'false'
          remove-android: 'false'
          remove-haskell: 'false'
          
          
      - name: Check out code base
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: env.BUILDKIT_STEP_LOG_MAX_SIZE=10000000
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build with Docker
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mohsen7s/tbb:fetchcargo1106
          file: tbb/Dockerfile
#          outputs: type=docker,dest=./dock_torimage.tar

   #       sudo find /home -type f -exec du --threshold=100000000 -h -a  {} +
