name: Tor Builder

on:
  push:
    paths:
        - '.github/workflows/tbbondocker.yml'

env:
  DEBIAN_FRONTEND: noninteractive
  #RBM_NUM_PROCS: 8

jobs:
  browser:
    name: Build Tor Browser
    runs-on: ubuntu-latest
    steps:
      
      - name: Free 80GB
        run: |
          sudo rm -rf "/usr/local/"
          sudo rm -rf "/usr/share/"
          sudo rm -rf "/opt/"
          
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 60000
          swap-size-mb: 8
          temp-reserve-mb: 8
          remove-dotnet: 'false'
          remove-android: 'false'
          remove-haskell: 'false'
    
    
      - name: Pull image and print hdd info
        run: |
          df -h
          docker pull mohsen7s/tbb:1106
          df -h
          
      - name: Check out code base
        shell: 'script -q -e -c "bash {0}"'
        run: |
          docker run -it -d --privileged --name tbb mohsen7s/tbb:1106
          docker exec -i tbb bash -c "cat /etc/subuid && cat /etc/subgid && chmod 4755 /usr/bin/newuidmap && chmod 4755 /usr/bin/newgidmap && echo tried  && cd tor-browser-build && make list_toolchain_updates-firefox-windows && echo 'make cargo_vendor-cbindgen' && make cargo_vendor-cbindgen && echo 'make cargo_vendor-lucetc' && make cargo_vendor-lucetc && echo 'make cargo_vendor-uniffi-rs' && make cargo_vendor-uniffi-rs && echo 'make cargo_vendor-cbindgen-android' && make cargo_vendor-cbindgen-android && echo 'make make cargo_vendor-cbindgen' && make cargo_vendor-application-services"
          
          
 
