name: Tor Builder

on:
  push:
    paths:
        - '.github/workflows/tbbondocker.yml'

env:
  DEBIAN_FRONTEND: noninteractive
  #RBM_NUM_PROCS: 8

jobs:
  browser:
    name: Build Tor Browser
    runs-on: ubuntu-latest
    steps:
      
      - name: Free 80GB
        run: |
          sudo rm -rf "/usr/local/"
          sudo rm -rf "/usr/share/"
          sudo rm -rf "/opt/"
          
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 60000
          swap-size-mb: 8
          temp-reserve-mb: 8
          remove-dotnet: 'false'
          remove-android: 'false'
          remove-haskell: 'false'
    
    
      - name: Pull image and print hdd info
        run: |
          df -h
          docker pull mohsen7s/tbb:1106
          df -h
          
      - name: Check out code base
        shell: 'script -q -e -c "bash {0}"'
        run: |
          docker run -it -d --privileged --name tbb mohsen7s/tbb:1106
          docker exec -i tbb bash -c "cd tor-browser-build &&  make nightly-src && du out/container-image/* -h && echo wintoolchain "


#          docker exec -i tbb bash -c "cd tor-browser-build &&  \
#          ./rbm/rbm build rust --target release --target torbrowser-windows-x86_64 && du out/container-image/* -h && \
#          ./rbm/rbm build cbindgen --target release --target torbrowser-windows-x86_64 && du out/container-image/* -h && \
#          ./rbm/rbm build lucetc --target release --target torbrowser-windows-x86_64 && du out/container-image/* -h && \
#          ./rbm/rbm build node --target release --target torbrowser-windows-x86_64 && du out/container-image/* -h && \
#          ./rbm/rbm build nasm --target release --target torbrowser-windows-x86_64 && du out/container-image/* -h && \
#          ./rbm/rbm build python --target release --target torbrowser-windows-x86_64 && du out/container-image/* -h && \    
#          ./rbm/rbm build clang --target release --target torbrowser-windows-x86_64 && du out/container-image/* -h && \
#          ./rbm/rbm build tor-launcher --target release --target torbrowser-windows-x86_64 && du out/container-image/* -h"
