name: Sample Run Include Syntax Json Format

on:
  push :
    paths:
        - '.github/workflows/testci.yml'
        
jobs: 
  job1:
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
      matrix:
        include:
          - data: 
            - include:
              - name: android
                steps:
                  - components: |
                     ./rbm/rbm build android-toolchain --target release --target torbrowser-android-armv7
                     ./rbm/rbm build clang --target release --target torbrowser-android-armv7
                  - components: |
                     ./rbm/rbm build rust --target release --target torbrowser-android-armv7
                     ./rbm/rbm build node --target release --target torbrowser-android-armv7
                  - components: |
                     ./rbm/rbm build fenix --target release --target torbrowser-android-armv7
                  - components: |
                     ./rbm/rbm build release --target release --target torbrowser-android-armv7
              - name: windows
                steps:
                  - components: |
                     ./rbm/rbm build mingw-w64 --target release --target torbrowser-windows-x86_64
                     ./rbm/rbm build clang --target release --target torbrowser-windows-x86_64
                  - components: |
                     ./rbm/rbm build rust --target release --target torbrowser-windows-x86_64
                     ./rbm/rbm build node --target release --target torbrowser-windows-x86_64
                  - components: |
                     ./rbm/rbm build firefox --target release --target torbrowser-windows-x86_64
                  - components: |
                     ./rbm/rbm build release --target release --target torbrowser-windows-x86_64
              - name: linux
                steps:
                  - components: |
                     ./rbm/rbm build gcc --target release --target torbrowser-linux-x86_64
                     ./rbm/rbm build clang --target release --target torbrowser-linux-x86_64
                  - components: |
                     ./rbm/rbm build rust --target release --target torbrowser-linux-x86_64
                     ./rbm/rbm build node --target release --target torbrowser-linux-x86_64
                  - components: |
                     ./rbm/rbm build firefox --target release --target torbrowser-linux-x86_64
                  - components: |
                     ./rbm/rbm build release --target release --target torbrowser-linux-x86_64
              - name: macosx
                steps:
                  - components: |
                     ./rbm/rbm build macosx-toolchain --target release --target torbrowser-osx-x86_64
#                     ./rbm/rbm build clang --target release --target torbrowser-osx-x86_64
                  - components: |
                     ./rbm/rbm build rust --target release --target torbrowser-osx-x86_64
                     ./rbm/rbm build node --target release --target torbrowser-osx-x86_64
                  - components: |
                     ./rbm/rbm build firefox --target release --target torbrowser-osx-x86_64
                  - components: |
                     ./rbm/rbm build release --target release --target torbrowser-osx-x86_64

    outputs:
       matrix: ${{ steps.setmatrix.outputs.matrix }}
    steps:
      - name: Set Dynamic Matrix
        id: setmatrix
#this patch inability of github workflow to parse multiline strings
        run: |        
          yamlAsJson='${{ toJSON(matrix.data[0]) }}'
          yamlAsJson="${yamlAsJson//'%'/'%25'}"
          yamlAsJson="${yamlAsJson//$'\n'/'%0A'}"
          yamlAsJson="${yamlAsJson//$'\r'/'%0D'}"
          echo "::set-output name=matrix::$yamlAsJson"
          
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.job1.outputs.matrix) }}

    steps:    

    - id: a
      run: echo JJOOBB ${{ job.container.id	 }}
    - run: echo Run ${{ matrix.steps[1].components }}    
 
