
name: CI Test Env

on:
  push :
    paths:
        - '.github/workflows/testci.yml'
      
      
jobs:
  stage2:
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
      matrix:
        include:          
          - name: windows
            target: torbrowser-windows-x86_64
            c1: mingw-w64
            c2: clang
              

              
    steps:
      - name: echo
        run: |
         echo ${{ matrix.c1 }} --target release --target ${{ matrix.target }}
         echo ${{ matrix.c2 }} --target release --target ${{ matrix.target }}
 
         
