name: Sample Run Include Syntax Json Format

on:
  push :
    paths:
        - '.github/workflows/testci.yml'
      
      
jobs: 
  job1:
    runs-on: ubuntu-latest
    
    strategy: 
      fail-fast: false
      matrix:
        include:
          - data: 
            - "name": "windows"
              "target": "torbrowser-windows-x86_64"
              "components":
                - "mingw-w64"
                - "clang"

            - "name": "android"
              "target": "torbrowser-android-armv7"
              "components":
                - "android-toolchain"
                - "clang"

    outputs:
       matrix: ${{ steps.setmatrix.outputs.matrix }}
    steps:
      - name: Set Dynamic Matrix
        id: setmatrix
        run: |
           matrixStringifiedObject="${{ toJSON(matrix.data) }}"
           echo "::set-output name=matrix::$matrixStringifiedObject"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.job1.outputs.matrix) }}
    steps:
    - run: echo Run ${{ join(matrix.components, './rbm/rbm build ') }}
 
