name: Sample Run Include Syntax Json Format

on:
  push :
    paths:
        - '.github/workflows/testci.yml'
      
      
jobs: 
  job2:
#    needs: job1
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
      matrix:
        include:          
          - name: windows
            target: torbrowser-windows-x86_64
            components:
              - mingw-w64
              - clang
              
          - name: android
            target: torbrowser-android-armv7
            components:
              - android-toolchain
              - clang
              
          - name: linux
            target: torbrowser-linux-x86_64
            components:
              - gcc
              - clang
              
          - name: macosx
            target: torbrowser-osx-x86_64
            components:
              - macosx-toolchain
              - clang          


    steps:
    - run: echo Run ${{ join(matrix.components, './rbm/rbm build ') }}
 
