
name: CI Test Env

on:
  push :
    paths:
        - '.github/workflows/testci.yml'
      
      
jobs:
  stage2:
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
      matrix:
        include:          
          - name: windows
            target: torbrowser-windows-x86_64
            components: |
              mingw-w64
              clang
              
          - name: android
            target: torbrowser-android-armv7
            components: |
              android-toolchain
              clang
              
          - name: linux
            target: torbrowser-linux-x86_64
            components: |
              gcc
              clang
              
          - name: macosx
            target: torbrowser-osx-x86_64
            components: |
              macosx-toolchain
              clang        
    steps:
      - name: echo
        run: |
          echo 1
  build:
    name: Build Centos 
    runs-on: ubuntu-latest
    steps:

    - name: build
      run: |
         echo ${{ matrix.components[0] }} --target release --target ${{ matrix.target }}
         echo ${{ matrix.components[1] }} --target release --target ${{ matrix.target }}
         echo ${{ matrix.name }}
         echo ${{ matrix.name }}
         
