name: Tree tbb

on:
  push :
    paths:
        - '.github/workflows/treetbb.yml'

env:
  DOCKER_BUILDKIT: 1
  DEBIAN_FRONTEND: noninteractive
  FIREFOX_STEP1: '  - filename: get-moz-build-date'

jobs:
  #Consumed 1:15
  stage1:
    runs-on: ubuntu-latest
    steps:
      - name: Build Fetch
        uses: mohsen7s/runner-prune-except-docker@main
        with:
          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          use-image-name: ubuntu:22.04
          step-image-name: mohsen7s/tbb:step1
          run-command: |
            echo IyEvYmluL3NoCmNkIHRvci1icm93c2VyLWJ1aWxkCnJtIC1mciBwcm9qZWN0cy9jb21wb25lbnQtc3RlcC1idWlsZGVyCm1rZGlyIHByb2plY3RzL2NvbXBvbmVudC1zdGVwLWJ1aWxkZXIKZWNobyAkJyMhL2Jpbi9zaCBcbnNldCAtZScgfCB0ZWUgcHJvamVjdHMvY29tcG9uZW50LXN0ZXAtYnVpbGRlci9idWlsZApzZWQgLWUgIi9eJDQvLC9eRU5ET0ZGSUxFL2QiIHByb2plY3RzLyQxL2NvbmZpZyA+IHByb2plY3RzL2NvbXBvbmVudC1zdGVwLWJ1aWxkZXIvY29uZmlnCi4vcmJtL3JibSBidWlsZCBjb21wb25lbnQtc3RlcC1idWlsZGVyIC0tdGFyZ2V0ICQyIC0tdGFyZ2V0ICQzCnJtIC1mciBwcm9qZWN0cy9jb21wb25lbnQtc3RlcC1idWlsZGVyCg== | base64 --decode > build.sh
            cat build.sh
            chmod +x build.sh
            apt-get update
            apt install -y -qq wget git build-essential vim curl
            apt install -y -qq libyaml-libyaml-perl libtemplate-perl libdatetime-perl \
                               libio-handle-util-perl libio-all-perl \
                               libio-captureoutput-perl libjson-perl libpath-tiny-perl \
                               libstring-shellquote-perl libsort-versions-perl \
                               libdigest-sha-perl libdata-uuid-perl libdata-dump-perl \
                               libfile-copy-recursive-perl libfile-slurp-perl git \
                               uidmap
            rm -rf /var/lib/apt/lists/* 
            usermod --add-subuids 1000000-1099999 --add-subgids 1000000-1099999 root
            git config --global http.postBuffer 524288000
            git config --global https.postBuffer 524288000
            git config --global http.sslVerify false
            git config --global https.sslVerify false
            git config --global core.compression -1
            git clone https://gitlab.torproject.org/tpo/applications/tor-browser-build.git
            cd tor-browser-build
            make submodule-update
            cd rbm
            rm -fr container
            wget https://gitlab.torproject.org/tpo/applications/rbm/-/raw/cad40965ce1204936a0df71c405bf0393b534ef9/container
            chmod 777 container
            cd ..
            make fetch
        
  #Consumed X:XX
  android1:
    runs-on: ubuntu-latest
    needs: stage1
    steps:
      - name: Build Android Compiler
        uses: mohsen7s/runner-prune-except-docker@main
        with:
          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          use-image-name: mohsen7s/tbb:step1
          step-image-name: mohsen7s/tbb:step1.android1
          run-command: |
            cd tor-browser-build
            make get_gradle_dependencies_list-application-services          
#            ./build.sh 'geckoview' 'release' 'torbrowser-android-armv7' '  - project: node'
  
  #Consumed X:XX
  android2:
    runs-on: ubuntu-latest
    needs: android1
    steps:
      - name: Build Android Compiler
        uses: mohsen7s/runner-prune-except-docker@main
        with:
          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          use-image-name: mohsen7s/tbb:step1.android1
          step-image-name: mohsen7s/tbb:step1.android2
          run-command: |
            cd tor-browser-build
            make get_gradle_dependencies_list-android-components            
#            ./build.sh 'fenix' 'release' 'torbrowser-android-armv7' '  - name: application-services'

  #Consumed X:XX
  android3:
    runs-on: ubuntu-latest
    needs: android2
    steps:
      - name: Build Android Compiler
        uses: mohsen7s/runner-prune-except-docker@main
        with:
          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          use-image-name: mohsen7s/tbb:step1.android2
          step-image-name: mohsen7s/tbb:step1.android3
          run-command: |
            cd tor-browser-build
            make get_gradle_dependencies_list-fenix           
#            ./build.sh 'fenix' 'release' 'torbrowser-android-armv7' '  - name: geckoview'
 
  #Consumed X:XX
  android4:
    runs-on: ubuntu-latest
    needs: android3
    steps:
      - name: Build Android Compiler
        uses: mohsen7s/runner-prune-except-docker@main
        with:
          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          use-image-name: mohsen7s/tbb:step1.android3
          step-image-name: mohsen7s/tbb:step1.android4
          run-command: |
            ./build.sh 'fenix' 'release' 'torbrowser-android-armv7' '  - project: tor-onion-proxy-library'
 


  #Consumed 4:15
  windows1:
    runs-on: ubuntu-latest
    needs: stage1
    steps:
      - name: Build Windows Compiler
        uses: mohsen7s/runner-prune-except-docker@main
        with:
          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          use-image-name: mohsen7s/tbb:step1
          step-image-name: mohsen7s/tbb:step1.windows1
          run-command: |
            ./build.sh 'firefox' 'release' 'torbrowser-windows-x86_64' '  - filename: get-moz-build-date'

  #Consumed X:XX
  windows2:
    runs-on: ubuntu-latest
    needs: windows1
    steps:
      - name: Build Windows Rust
        uses: mohsen7s/runner-prune-except-docker@main
        with:
          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          use-image-name: mohsen7s/tbb:step1.windows1
          step-image-name: mohsen7s/tbb:step1.windows2
          run-command: |  
            echo IyEvYmluL3NoCmNkIHRvci1icm93c2VyLWJ1aWxkCnJtIC1mciBwcm9qZWN0cy9jb21wb25lbnQtc3RlcC1idWlsZGVyCiNta2RpciBwcm9qZWN0cy9jb21wb25lbnQtc3RlcC1idWlsZGVyCiNlY2hvICQnIyEvYmluL3NoIFxuc2V0IC1lJyB8IHRlZSBwcm9qZWN0cy9jb21wb25lbnQtc3RlcC1idWlsZGVyL2J1aWxkCiNzZWQgLWUgIi9eJDQvLC9eRU5ET0ZGSUxFL2QiIHByb2plY3RzLyQxL2NvbmZpZyA+IHByb2plY3RzL2NvbXBvbmVudC1zdGVwLWJ1aWxkZXIvY29uZmlnCmNwIC1yIHByb2plY3RzLyQxIHByb2plY3RzL2NvbXBvbmVudC1zdGVwLWJ1aWxkZXIKbXYgcHJvamVjdHMvY29tcG9uZW50LXN0ZXAtYnVpbGRlci9jb25maWcgcHJvamVjdHMvY29tcG9uZW50LXN0ZXAtYnVpbGRlci90bXBjZmcKc2VkIC1lICIvXiQ0LywvXkVORE9GRklMRS9kIiBwcm9qZWN0cy9jb21wb25lbnQtc3RlcC1idWlsZGVyL3RtcGNmZyA+IHByb2plY3RzL2NvbXBvbmVudC1zdGVwLWJ1aWxkZXIvY29uZmlnCi4vcmJtL3JibSBidWlsZCBjb21wb25lbnQtc3RlcC1idWlsZGVyIC0tdGFyZ2V0ICQyIC0tdGFyZ2V0ICQzCiNybSAtZnIgcHJvamVjdHMvY29tcG9uZW50LXN0ZXAtYnVpbGRlcgo= | base64 --decode > build1.sh
            cat build1.sh
            chmod +x build1.sh
            ./build1.sh 'firefox' 'release' 'torbrowser-windows-x86_64' '  - project: clang'
   
  #Consumed 2:30 
  linux1:
    runs-on: ubuntu-latest
    needs: stage1
    steps:
      - name: Build Linux Compiler
        uses: mohsen7s/runner-prune-except-docker@main
        with:
          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          use-image-name: mohsen7s/tbb:step1
          step-image-name: mohsen7s/tbb:step1.linux1
          run-command: |
            ./build.sh 'firefox' 'release' 'torbrowser-linux-x86_64' '  - filename: get-moz-build-date'
  
  #Consumed X:XX
  linux2:
    runs-on: ubuntu-latest
    needs: linux1
    steps:
      - name: Build Linux Rust
        uses: mohsen7s/runner-prune-except-docker@main
        with:
          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          use-image-name: mohsen7s/tbb:step1.linux1
          step-image-name: mohsen7s/tbb:step1.linux2
          run-command: |
            echo IyEvYmluL3NoCmNkIHRvci1icm93c2VyLWJ1aWxkCnJtIC1mciBwcm9qZWN0cy9jb21wb25lbnQtc3RlcC1idWlsZGVyCiNta2RpciBwcm9qZWN0cy9jb21wb25lbnQtc3RlcC1idWlsZGVyCiNlY2hvICQnIyEvYmluL3NoIFxuc2V0IC1lJyB8IHRlZSBwcm9qZWN0cy9jb21wb25lbnQtc3RlcC1idWlsZGVyL2J1aWxkCiNzZWQgLWUgIi9eJDQvLC9eRU5ET0ZGSUxFL2QiIHByb2plY3RzLyQxL2NvbmZpZyA+IHByb2plY3RzL2NvbXBvbmVudC1zdGVwLWJ1aWxkZXIvY29uZmlnCmNwIC1yIHByb2plY3RzLyQxIHByb2plY3RzL2NvbXBvbmVudC1zdGVwLWJ1aWxkZXIKbXYgcHJvamVjdHMvY29tcG9uZW50LXN0ZXAtYnVpbGRlci9jb25maWcgcHJvamVjdHMvY29tcG9uZW50LXN0ZXAtYnVpbGRlci90bXBjZmcKc2VkIC1lICIvXiQ0LywvXkVORE9GRklMRS9kIiBwcm9qZWN0cy9jb21wb25lbnQtc3RlcC1idWlsZGVyL3RtcGNmZyA+IHByb2plY3RzL2NvbXBvbmVudC1zdGVwLWJ1aWxkZXIvY29uZmlnCi4vcmJtL3JibSBidWlsZCBjb21wb25lbnQtc3RlcC1idWlsZGVyIC0tdGFyZ2V0ICQyIC0tdGFyZ2V0ICQzCiNybSAtZnIgcHJvamVjdHMvY29tcG9uZW50LXN0ZXAtYnVpbGRlcgo= | base64 --decode > build1.sh
            cat build1.sh
            chmod +x build1.sh
            ./build1.sh 'firefox' 'release' 'torbrowser-linux-x86_64' '  - project: clang'
            
            
  #Consumed X:XX
  osx1:
    runs-on: ubuntu-latest
    needs: stage1
    steps:
      - name: Build OSX Compiler
        uses: mohsen7s/runner-prune-except-docker@main
        with:
          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          use-image-name: mohsen7s/tbb:step1
          step-image-name: mohsen7s/tbb:step1.osx1
          run-command: |
            ./build.sh 'firefox' 'release' 'torbrowser-osx-x86_64' '  - filename: get-moz-build-date'

 
  #Consumed X:XX
  osx2:
    runs-on: ubuntu-latest
    needs: osx1
    steps:
      - name: Build OSX Rust
        uses: mohsen7s/runner-prune-except-docker@main
        with:
          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          use-image-name: mohsen7s/tbb:step1.osx1
          step-image-name: mohsen7s/tbb:step1.osx2
          run-command: |
            echo IyEvYmluL3NoCmNkIHRvci1icm93c2VyLWJ1aWxkCnJtIC1mciBwcm9qZWN0cy9jb21wb25lbnQtc3RlcC1idWlsZGVyCiNta2RpciBwcm9qZWN0cy9jb21wb25lbnQtc3RlcC1idWlsZGVyCiNlY2hvICQnIyEvYmluL3NoIFxuc2V0IC1lJyB8IHRlZSBwcm9qZWN0cy9jb21wb25lbnQtc3RlcC1idWlsZGVyL2J1aWxkCiNzZWQgLWUgIi9eJDQvLC9eRU5ET0ZGSUxFL2QiIHByb2plY3RzLyQxL2NvbmZpZyA+IHByb2plY3RzL2NvbXBvbmVudC1zdGVwLWJ1aWxkZXIvY29uZmlnCmNwIC1yIHByb2plY3RzLyQxIHByb2plY3RzL2NvbXBvbmVudC1zdGVwLWJ1aWxkZXIKbXYgcHJvamVjdHMvY29tcG9uZW50LXN0ZXAtYnVpbGRlci9jb25maWcgcHJvamVjdHMvY29tcG9uZW50LXN0ZXAtYnVpbGRlci90bXBjZmcKc2VkIC1lICIvXiQ0LywvXkVORE9GRklMRS9kIiBwcm9qZWN0cy9jb21wb25lbnQtc3RlcC1idWlsZGVyL3RtcGNmZyA+IHByb2plY3RzL2NvbXBvbmVudC1zdGVwLWJ1aWxkZXIvY29uZmlnCi4vcmJtL3JibSBidWlsZCBjb21wb25lbnQtc3RlcC1idWlsZGVyIC0tdGFyZ2V0ICQyIC0tdGFyZ2V0ICQzCiNybSAtZnIgcHJvamVjdHMvY29tcG9uZW50LXN0ZXAtYnVpbGRlcgo= | base64 --decode > build1.sh
            cat build1.sh
            chmod +x build1.sh            
            ./build1.sh 'firefox' 'release' 'torbrowser-osx-x86_64' '  - project: clang'




#            ./rbm/rbm build gradle --target release --target torbrowser-android-armv7
#            ./rbm/rbm build binutils --target release --target torbrowser-android-armv7
#            ./rbm/rbm build rust --target release --target torbrowser-android-armv7
#            ./rbm/rbm build cbindgen --target release --target torbrowser-android-armv7
#            ./rbm/rbm build node --target release --target torbrowser-android-armv7
#            ./rbm/rbm build nasm --target release --target torbrowser-android-armv7
#

