name: Tree tbb

on:
  push :
    paths:
        - '.github/workflows/treetbb.yml'

env:
  DOCKER_BUILDKIT: 1
  DEBIAN_FRONTEND: noninteractive

jobs:
  stage1:
    runs-on: ubuntu-latest
    steps:
      - name: Build Fetch
        uses: mohsen7s/runner-prune-except-docker@main
        with:
          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          use-image-name: ubuntu:22.04
          step-image-name: mohsen7s/tbb:ci1
          run-command: |
            apt-get update
            apt install -y -qq wget git build-essential vim curl
            apt install -y -qq libyaml-libyaml-perl libtemplate-perl libdatetime-perl \
                               libio-handle-util-perl libio-all-perl \
                               libio-captureoutput-perl libjson-perl libpath-tiny-perl \
                               libstring-shellquote-perl libsort-versions-perl \
                               libdigest-sha-perl libdata-uuid-perl libdata-dump-perl \
                               libfile-copy-recursive-perl libfile-slurp-perl git \
                               uidmap
            rm -rf /var/lib/apt/lists/* 
            usermod --add-subuids 1000000-1099999 --add-subgids 1000000-1099999 root
            git config --global http.postBuffer 524288000
            git config --global https.postBuffer 524288000
            git config --global http.sslVerify false
            git config --global https.sslVerify false
            git config --global core.compression -1
            git clone https://gitlab.torproject.org/tpo/applications/tor-browser-build.git
            cd tor-browser-build
            make submodule-update
            cd rbm
            rm -fr container
            wget https://gitlab.torproject.org/tpo/applications/rbm/-/raw/cad40965ce1204936a0df71c405bf0393b534ef9/container
            chmod 777 container
            cd ..
            make fetch

#  stage2:
#    runs-on: ubuntu-latest
#    needs: stage1
#    steps:
#      - name: Build Android Toolchain
#        uses: mohsen7s/runner-prune-except-docker@main
#        with:
#          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
#          docker-password: ${{ secrets.DOCKERHUB_PASSWORD }}
#          use-image-name: mohsen7s/tbb:level1
#          step-image-name: mohsen7s/tbb:level2
#          run-command: |
#            cd tor-browser-build
#            
#  stage3:
#    runs-on: ubuntu-latest
#    needs: stage2
#    steps:
#      - name: Build 3
#        uses: mohsen7s/runner-prune-except-docker@main
#        with:
#          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
#          docker-password: ${{ secrets.DOCKERHUB_PASSWORD }}
#          use-image-name: mohsen7s/tbb:level2
#          step-image-name: mohsen7s/tbb:level3
#          run-command: |
#            cd tor-browser-build
#
#            
##  stage4:
##    runs-on: ubuntu-latest
##    needs: stage3
##    steps:
##      - name: Build 4
##        uses: mohsen7s/runner-prune-except-docker@main
##        with:
##          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
##          docker-password: ${{ secrets.DOCKERHUB_PASSWORD }}
##          use-image-name: mohsen7s/tbb:stage3
##          step-image-name: mohsen7s/tbb:stage4
##          run-command: |
##            cd tor-browser-build
##            rm -fr logs out/container-image/
##            du --max-depth=2 .
## 
#      
#
##            ./rbm/rbm build gradle --target release --target torbrowser-android-armv7
##            ./rbm/rbm build binutils --target release --target torbrowser-android-armv7
##            ./rbm/rbm build rust --target release --target torbrowser-android-armv7
##            ./rbm/rbm build cbindgen --target release --target torbrowser-android-armv7
##            ./rbm/rbm build node --target release --target torbrowser-android-armv7
##            ./rbm/rbm build nasm --target release --target torbrowser-android-armv7
##
#
