name: Tree tbb

on:
  push :
    paths:
        - '.github/workflows/treetbb.yml'

env:
  DOCKER_BUILDKIT: 1
  DEBIAN_FRONTEND: noninteractive
  FIREFOX_STEP1: '  - filename: get-moz-build-date'

jobs:
  stage1:
    runs-on: ubuntu-latest
    steps:
      - name: Build Fetch
        uses: mohsen7s/runner-prune-except-docker@main
        with:
          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          use-image-name: ubuntu:22.04
          step-image-name: mohsen7s/tbb:step1
          run-command: |
            apt-get update
            apt install -y -qq wget git build-essential vim curl
            apt install -y -qq libyaml-libyaml-perl libtemplate-perl libdatetime-perl \
                               libio-handle-util-perl libio-all-perl \
                               libio-captureoutput-perl libjson-perl libpath-tiny-perl \
                               libstring-shellquote-perl libsort-versions-perl \
                               libdigest-sha-perl libdata-uuid-perl libdata-dump-perl \
                               libfile-copy-recursive-perl libfile-slurp-perl git \
                               uidmap
            rm -rf /var/lib/apt/lists/* 
            usermod --add-subuids 1000000-1099999 --add-subgids 1000000-1099999 root
            git config --global http.postBuffer 524288000
            git config --global https.postBuffer 524288000
            git config --global http.sslVerify false
            git config --global https.sslVerify false
            git config --global core.compression -1
            git clone https://gitlab.torproject.org/tpo/applications/tor-browser-build.git
            
            cat >> build.sh << EOF
            #!/bin/sh
            cd tor-browser-build
            rm -fr projects/component-step-builder
            mkdir projects/component-step-builder
            echo $'#!/bin/sh \nset -e' | tee projects/component-step-builder/build
            sed -e "/^\$4/,/^ENDOFFILE/d" projects/\$1/config > projects/component-step-builder/config
            ./rbm/rbm build component-step-builder --target \$2 --target \$3
            rm -fr projects/component-step-builder
            EOF
            
            cat build.sh 
            cd tor-browser-build
            make submodule-update
            cd rbm
            rm -fr container
            wget https://gitlab.torproject.org/tpo/applications/rbm/-/raw/cad40965ce1204936a0df71c405bf0393b534ef9/container
            chmod 777 container
            cd ..
            make fetch
            
#  stage2:
#    runs-on: ubuntu-latest
#    needs: stage1
#    steps:
#      - name: Make Vendor
#        uses: mohsen7s/runner-prune-except-docker@main
#        with:
#          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
#          docker-password: ${{ secrets.DOCKERHUB_PASSWORD }}
#          use-image-name: mohsen7s/tbb:ci1
#          step-image-name: mohsen7s/tbb:ci2
#          run-command: |
#            cd tor-browser-build  
#            make cargo_vendor-application-services
#            make cargo_vendor-cbindgen-android
#            make cargo_vendor-cbindgen
#            make cargo_vendor-lucetc
#            make cargo_vendor-uniffi-rs
#            rm -fr logs out/container-image/
 
  android1:
    runs-on: ubuntu-latest
    needs: stage1
    steps:
      - name: Build Android Compiler
        uses: mohsen7s/runner-prune-except-docker@main
        with:
          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          use-image-name: mohsen7s/tbb:step1
          step-image-name: mohsen7s/tbb:step1.android1
          run-command: |
            ./firefox-step.sh 'fenix' 'release' 'torbrowser-android-armv7' '  - project: gradle'

#  stage1-android2:
#    runs-on: ubuntu-latest
#    needs: stage1-android1
#    steps:
#      - name: Build Android X
#        uses: mohsen7s/runner-prune-except-docker@main
#        with:
#          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
#          docker-password: ${{ secrets.DOCKERHUB_PASSWORD }}
#          use-image-name: mohsen7s/tbb:ci1.android1
#          step-image-name: mohsen7s/tbb:ci1.android2
#          run-command: |
#            cd tor-browser-build
#            #./rbm/rbm build android-toolchain --target release --target torbrowser-android-armv7
#

  linux1:
    runs-on: ubuntu-latest
    needs: stage1
    steps:
      - name: Build Linux Compiler
        uses: mohsen7s/runner-prune-except-docker@main
        with:
          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          use-image-name: mohsen7s/tbb:step1
          step-image-name: mohsen7s/tbb:step1.linux1
          run-command: |
            ./firefox-step.sh 'firefox' 'release' 'torbrowser-linux-x86_64' '  - filename: get-moz-build-date'
            
            

#  stage1-linux2:
#    runs-on: ubuntu-latest
#    needs: stage1-linux1
#    steps:
#      - name: Build Linux X
#        uses: mohsen7s/runner-prune-except-docker@main
#        with:
#          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
#          docker-password: ${{ secrets.DOCKERHUB_PASSWORD }}
#          use-image-name: mohsen7s/tbb:ci1.linux1
#          step-image-name: mohsen7s/tbb:ci1.linux2
#          run-command: |
#            cd tor-browser-build
#            #./rbm/rbm build gcc --target release --target torbrowser-linux-x86_64
#

  stage1-windows1:
    runs-on: ubuntu-latest
    needs: stage1
    steps:
      - name: Build Windows Compiler
        uses: mohsen7s/runner-prune-except-docker@main
        with:
          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          use-image-name: mohsen7s/tbb:step1
          step-image-name: mohsen7s/tbb:step1.windows1
          run-command: |
            ./firefox-step.sh 'firefox' 'release' 'torbrowser-windows-x86_64' '  - filename: get-moz-build-date'
            
#  stage1-windows2:
#    runs-on: ubuntu-latest
#    needs: stage1-windows1
#    steps:
#      - name: Build Windows X
#        uses: mohsen7s/runner-prune-except-docker@main
#        with:
#          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
#          docker-password: ${{ secrets.DOCKERHUB_PASSWORD }}
#          use-image-name: mohsen7s/tbb:ci1.windows1
#          step-image-name: mohsen7s/tbb:ci1.windows2
#          run-command: |
#            cd tor-browser-build
#            #./rbm/rbm build mingw-w64 --target release --target torbrowser-windows-x86_64
#

  stage1-osx1:
    runs-on: ubuntu-latest
    needs: stage1
    steps:
      - name: Build OSX Compiler
        uses: mohsen7s/runner-prune-except-docker@main
        with:
          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          use-image-name: mohsen7s/tbb:step1
          step-image-name: mohsen7s/tbb:step1.osx1
          run-command: |
            ./firefox-step.sh 'firefox' 'release' 'torbrowser-osx-x86_64' '  - filename: get-moz-build-date'



#  stage1-osx2:
#    runs-on: ubuntu-latest
#    needs: stage1-osx1
#    steps:
#      - name: Build OSX X
#        uses: mohsen7s/runner-prune-except-docker@main
#        with:
#          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}
#          docker-password: ${{ secrets.DOCKERHUB_PASSWORD }}
#          use-image-name: mohsen7s/tbb:ci1.osx1
#          step-image-name: mohsen7s/tbb:ci1.osx2
#          run-command: |
#            cd tor-browser-build
#            #./rbm/rbm build macosx-toolchain --target release --target torbrowser-osx-x86_64
#











#            ./rbm/rbm build gradle --target release --target torbrowser-android-armv7
#            ./rbm/rbm build binutils --target release --target torbrowser-android-armv7
#            ./rbm/rbm build rust --target release --target torbrowser-android-armv7
#            ./rbm/rbm build cbindgen --target release --target torbrowser-android-armv7
#            ./rbm/rbm build node --target release --target torbrowser-android-armv7
#            ./rbm/rbm build nasm --target release --target torbrowser-android-armv7
#



